spring:
  datasource:
    url: jdbc:h2:mem:mybox
    username: "sa"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

file:
  storage-directory: /Users/jaeyeon/Documents/github/numble-mybox-server/storage
