#!/bin/sh
# 1. 변경된 파일들 이름만 추출하여 저장
targetFiles=$(git diff --staged --name-only)
# SpotlessApply 실행
echo "Apply Spotless.."
./gradlew spotlessApply --daemon
# 3. 변경사항이 발생한 파일들 다시 git add
for file in $targetFiles; do
  if test -f "$file"; then
    git add $file
  fi
done
