# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Java CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checkstyle:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v3

      - name: Filter Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
              - 'build.gradle'
              - 'src/**'

      - name: Checkstyle
        if: steps.changes.outputs.application == 'true'
        uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          checkstyle_config: ${{ github.workspace }}/config/checkstyle/naver-checkstyle-rules.xml
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v3

      - name: Filter Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
              - 'build.gradle'
              - 'src/**'

      - name: Set up JDK 17
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'

      - name: Build with Gradle
        if: steps.changes.outputs.application == 'true'
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Add coverage to PR
        if: steps.changes.outputs.application == 'true'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage Report
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          paths: |
            ${{ github.workspace }}/**/build/jacoco/jacoco.xml

      - name: Style Check
        if: steps.changes.outputs.application == 'true'
        run: |
          ./gradlew spotlessCheck
