# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Pull Request Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2

      - name: JDK 설치
        uses: actions/setup-java@v3

        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'

      - name: Gradle Build
        run: ./gradlew build --parallel

      # Generate Jacoco coverage report after building the project.
      - name: Generate Jacoco coverage report
        run: ./gradlew jacocoTestReport

      # Upload the generated Jacoco coverage report to Codecov.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

        with:
          token : ${{ secrets.CODECOV_TOKEN }}
          file : ./build/jacoco/jacoco.xml


  style-test:
    runs-on : ubuntu-latest

    steps :

      - name : Git Checkout
        uses : actions/checkout@v3.0.2

      - name : JDK 설치
        uses : actions/setup-java@v3

        with :
          distribution : zulu
          java-version : 17
          cache : 'gradle'

      # Check the code style after setting up JDK.
      - name : Style Check
        run : ./gradlew spotlessCheck

      - name: Apply Spotless
        run: ./gradlew spotlessApply
